name: OpenServerManagement
version: '1.0'
main: jp.reitou_mugicha.openServerManagement.OpenServerManagement
api-version: '1.21'
author: "reitou_mugicha"

commands:
  fakechat:
    description: プレイヤーのチャットを偽装します。
    usage: /fakechat <対象> <内容>
    aliases:
      - fchat
      - impersonate
      - fc
  payexperience:
    description: プレイヤーに経験値を渡します。
    usage: /payexperience <対象> <経験値>
    aliases:
      - payexp
      - payxp
      - pxp
      - pe
    permission: payexperience
  craftwar:
    description: CraftWarを管理するコマンドです。
    usage: /craftwar <start|stop|reroll>
    aliases:
      - cwar
      - cw
    permission: craftwar
  sleep:
    description: その場で寝ます。
    usage: /sleep
    aliases:
      - sleephere
  opencustomenderchest:
    description: 拡張エンダーチェストを開きます。
    usage: /opencustomenderchest <対象>
    aliases:
      - opencenderchest
      - ocec
      - oce
      - oc
    permission: opencustomenderchest

permissions:
  payexperience:
    description: PayExperienceのコマンド権限
    default: op
  craftwar:
    description: CraftWarのコマンド管理
    default: op
  opencustomenderchest:
    default: op